### ISSUE TITLE
Feature Request : Include standard Alexa cards

### ISSUE THREAD

**Issue by likeadoc** [joanaz/MMM-MirrorMirrorOnTheWall#2]
Would it be possible to include the standard Alexa cards  (timer, player, etc.)that are displayed in the companion app/firetv app ?
Maybe as an iframe by pulling data from the layla.amazon.com api?

**Comment by likeadoc** [comment]
https://www.amazon.com/gp/html-forms-controller/Display-Cards-for-Alexa seems like its limited to commercial use atm.

**Comment by joanaz** [comment]
it's a cool idea, but you can just use iFrame to see the amazon alexa website.
