### ISSUE TITLE
Close Magic Mirror

### ISSUE THREAD

**Issue by asifma** [joanaz/MMM-MirrorMirrorOnTheWall#6]
Hi, I had to edit the "SampleUtterances.txt" in the Alexa skill.
I think you missed:
TurnOffModuleIntent close {magic mirror|moduleName}
TurnOffModuleIntent hide {magic mirror|moduleName}
TurnOffModuleIntent turn off {magic mirror|moduleName}

etc. 

But now its working :)! After I added it to the Alexa Skill. Now i can close the Magic mirror module. 
For example, when I want to clean the mirror from Images retrieved from the skill

Love the skill by the way! GREAT JOB!

**Comment by joanaz** [comment]
the existing sample utterances should make any module name work, but alexa's voice recognition is not perfect, so adding more samples would always be better. Glad you enjoyed this module, thanks!
